In [19]:
import numpy as np
import matplotlib.pyplot as plt

from Metropolis import *
import HarmonicOscillator as oscillator
import Hatom as Hydrogen
import Helium as Helium

System = oscillator

alpha = System.alpha

D = System.dimension

N_tries = 30000
N_walkers = 400


E_a = np.zeros(len(alpha))
E_var = np.zeros(len(alpha))

for i in range(len(alpha)):
    f = lambda R: System.trialWaveFunction(alpha[i], R)

    rn, accept_rate = metropolis_algorithm(f, N_tries, N_walkers, D)
    E = System.E_loc(alpha[i], rn)
    E_a[i] = np.mean(E)
    E_var[i] = np.var(E)

print("This cell gives the energy and variance of the harmonic oscilator in 1D:")
print()
print("E(\N{greek small letter alpha})")
print(E_a)
print("var(E(\N{greek small letter alpha})))")
print(E_var)
print(f"Acceptance rate : {accept_rate}")

This cell gives the energy and variance of the harmonic oscilator in 1D:

E(α)
[0.51243142 0.50277336 0.5        0.50216659 0.50849598]
var(E(α)))
[0.02526098 0.00557779 0.         0.00457696 0.01674623]
Acceptance rate : 0.5231323333333333


In [18]:
import numpy as np
import matplotlib.pyplot as plt

from Metropolis import *
import HarmonicOscillator as oscillator
import Hatom as Hydrogen
import Helium as Helium

System = Hydrogen

alpha = System.alpha

D = System.dimension

N_tries = 30000
N_walkers = 400


E_a = np.zeros(len(alpha))
E_var = np.zeros(len(alpha))

for i in range(len(alpha)):
    f = lambda R: System.trialWaveFunction(alpha[i], R)

    rn, accept_rate = metropolis_algorithm(f, N_tries, N_walkers, D)
    E = System.E_loc(alpha[i], rn)
    E_a[i] = np.mean(E)
    E_var[i] = np.var(E)

print("This cell gives the energy and variance of the Hydrogen atom in 3D:")
print()
print("E(\N{greek small letter alpha})")
print(E_a)
print("var(E(\N{greek small letter alpha})))")
print(E_var)
print(f"Acceptance rate : {accept_rate}")

This cell gives the energy and variance of the Hydrogen atom in 3D:

E(α)
[-0.47673305 -0.49355804 -0.5        -0.49612513 -0.48189865]
var(E(α)))
[0.02147738 0.00734379 0.         0.01204095 0.05275765]
Acceptance rate : 0.8007894166666667


In [20]:
import numpy as np
import matplotlib.pyplot as plt

from Metropolis import *
import HarmonicOscillator as oscillator
import Hatom as Hydrogen
import Helium as Helium

System = Helium

alpha = System.alpha

D = System.dimension

N_tries = 30000
N_walkers = 400


E_a = np.zeros(len(alpha))
E_var = np.zeros(len(alpha))

for i in range(len(alpha)):
    f = lambda R: System.trialWaveFunction(alpha[i], R)

    rn, accept_rate = metropolis_algorithm(f, N_tries, N_walkers, D)
    E = System.E_loc(alpha[i], rn)
    E_a[i] = np.mean(E)
    E_var[i] = np.var(E)

print("This cell gives the energy and variance of the Helium atom in 3D:")
print("E(\N{greek small letter alpha})")
print(E_a)
print("var(E(\N{greek small letter alpha})))")
print(E_var)
print(f"Acceptance rate : {accept_rate}")

This cell gives the energy and variance of the Helium atom in 3D:
E(α)
[-2.87015808 -2.86154614 -2.85704725 -2.85383506 -2.84805155 -2.83985963
 -2.83056136 -2.82328586]
var(E(α)))
[0.18328815 0.16263956 0.14717319 0.13421303 0.12427957 0.11577997
 0.11102609 0.10641076]
Acceptance rate : 0.19467558333333335
